import { readFile } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import assert from 'node:assert/strict';
import { test } from 'node:test';
const source = (await readFile(new URL('./worker.mjs', import.meta.url),'utf8')).replace("import panel from './panel.html';",'const panel = "panel";');
const { default:worker, authorized } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const payload = {name:'Prueba',phone:'0000000000',project:'Una invitación digital',message:'Referencia de prueba'};
const png = new File([Uint8Array.from([137,80,78,71,13,10,26,10,0])],'referencia.png',{type:'image/png'});
async function environment() {
  const db = new DatabaseSync(':memory:');
  db.exec('CREATE TABLE submissions(id INTEGER PRIMARY KEY, name TEXT,email TEXT,phone TEXT,project TEXT,ideal_date TEXT,message TEXT,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)');
  db.exec(await readFile(new URL('./schema.sql',import.meta.url),'utf8'));
  const objects = new Map();
  const prepare = sql => ({ bind(...values) { return { run() { const r=db.prepare(sql).run(...values); return { meta:{ last_row_id:Number(r.lastInsertRowid) } }; }, first() { return db.prepare(sql).get(...values); } }; }, all() { return { results:db.prepare(sql).all() }; } });
  return { db,objects,ACCESS_TEAM_DOMAIN:'example.cloudflareaccess.com',ACCESS_AUD:'app',DB:{prepare,batch:async statements=>{db.exec('BEGIN');try{const result=statements.map(s=>s.run());db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}},ATTACHMENTS:{async put(key,stream){objects.set(key,await new Response(stream).arrayBuffer())},async delete(key){objects.delete(key)}} };
}
function request(files, values=payload) { const form=new FormData();form.append('payload',JSON.stringify(values));files.forEach(f=>form.append('attachments',f));return new Request('https://api.rotfstudio.com/submit',{method:'POST',headers:{Origin:'http://127.0.0.1:4173'},body:form}); }
test('three attachments belong to one submission, old text-only requests still work',async()=>{const env=await environment();let r=await worker.fetch(request([png,png,png]),env);assert.equal(r.status,201);assert.equal((await r.json()).attachmentCount,3);assert.equal(env.objects.size,3);assert.deepEqual(env.db.prepare('SELECT DISTINCT submission_id FROM attachments').all().map(x=>x.submission_id),[1]);r=await worker.fetch(new Request('https://api.rotfstudio.com/submit',{method:'POST',headers:{Origin:'https://rotfstudio.com','Content-Type':'application/json'},body:JSON.stringify(payload)}),env);assert.equal(r.status,201);assert.equal(env.db.prepare('SELECT count(*) AS n FROM submissions').get().n,2)});
test('spoofed files, excessive count and forbidden origins do not write',async()=>{const env=await environment();assert.equal((await worker.fetch(request([new File(['bad'],'bad.png',{type:'image/png'})]),env)).status,400);assert.equal((await worker.fetch(request([png,png,png,png]),env)).status,400);assert.equal((await worker.fetch(new Request('https://api.rotfstudio.com/submit',{method:'POST',headers:{Origin:'https://untrusted.example'},body:'{}'}),env)).status,403);assert.equal(env.objects.size,0);assert.equal(env.db.prepare('SELECT count(*) AS n FROM submissions').get().n,0)});
test('database failure rolls back submission and removes objects',async()=>{const env=await environment();env.db.exec('DROP TABLE attachments');assert.equal((await worker.fetch(request([png]),env)).status,500);assert.equal(env.objects.size,0);assert.equal(env.db.prepare('SELECT count(*) AS n FROM submissions').get().n,0)});
test('email headers cannot bypass panel or file authorization',async()=>{const env=await environment();for(const path of ['/admin','/admin/submissions','/admin/attachments/12345678-1234-1234-1234-123456789abc'])assert.equal((await worker.fetch(new Request('https://api.rotfstudio.com'+path,{headers:{'Cf-Access-Authenticated-User-Email':'spoof@example.com'}}),env)).status,401);assert.equal(await authorized(new Request('https://api.rotfstudio.com/admin',{headers:{'Cf-Access-Jwt-Assertion':'bad.token.value'}}),env),false)});
test('valid signature required and token audience/expiry checked',async()=>{const env=await environment();const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk=await crypto.subtle.exportKey('jwk',keys.publicKey);jwk.kid='test';const originalFetch=globalThis.fetch;globalThis.fetch=async()=>Response.json({keys:[jwk]});try{const token=async changes=>{const head=Buffer.from(JSON.stringify({alg:'RS256',kid:'test'})).toString('base64url');const body=Buffer.from(JSON.stringify({iss:'https://example.cloudflareaccess.com',aud:['app'],exp:Date.now()/1000+300,...changes})).toString('base64url');const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',keys.privateKey,new TextEncoder().encode(head+'.'+body));return new Request('https://api.rotfstudio.com/admin',{headers:{'Cf-Access-Jwt-Assertion':head+'.'+body+'.'+Buffer.from(signature).toString('base64url')}})};assert.equal(await authorized(await token({}),env),true);assert.equal(await authorized(await token({aud:['other']}),env),false);assert.equal(await authorized(await token({exp:1}),env),false)}finally{globalThis.fetch=originalFetch}});
